forecast_config:
  config_object:
    evaluate: true
    evaluation_config:
      gap: 0
      n_splits: 2
      prediction_interval: 0.95
    on_error: skip
  forecast_days: null
  table: ny_taxi_rides_h3_predict
  training_days: 180
input_data:
  exogenous_columns: []
  series_column: h3
  table: ny_taxi_rides_h3_train
  table_type: table
  target_column: pickups
  timestamp_column: pickup_time
model:
  comment: Forecast model for predicting trends.
  name: my_taxi_forecast_model
  tags:
    environment: development
    team: data_science
output:
  table: taxi_forecast_results
