forecast_config:
  config_object:
    evaluate: true
    evaluation_config:
      gap: 0
      n_splits: 2
      prediction_interval: 0.95
    on_error: skip
  forecast_days: null
  table: ny_taxi_rides_h3_predict
  training_days: 60
input_data:
  exogenous_columns:
  - SCHOOL_HOLIDAY
  - PUBLIC_HOLIDAY
  - SPORT_EVENT
  series_column: H3
  table: NY_TAXI_RIDES_H3_TRAIN
  table_type: table
  target_column: PICKUPS
  timestamp_column: PICKUP_TIME
model:
  comment: Forecast model for predicting trends.
  name: my_forecast_model
  tags:
    environment: development
    team: data_science
output:
  table: NY_TAXI_RIDES_H3_TRAIN_FORECAST_RESULTS
