forecast_config:
  config_object:
    evaluate: true
    evaluation_config:
      gap: 0
      n_splits: 2
      prediction_interval: 0.95
    on_error: skip
  forecast_days: 30
  training_days: 180
input_data:
  exogenous_columns: []
  series_column: ''
  table: storage_usage_train
  table_type: table
  target_column: storage_gb
  timestamp_column: usage_date
model:
  comment: Forecast model for predicting trends.
  name: my_forecast_model
  tags:
    environment: development
    team: data_science
output:
  table: storage_forecast_results
