model:
  name: my_taxi_forecast_model
  tags:
    environment: production
    team: data_science
  comment: "Forecast model for predicting sales trends."

input_data:
  table: ny_taxi_rides_h3_train
  table_type: table # or view
  timestamp_column: pickup_time
  target_column: pickups
  series_column: h3  # Set to column name for multiple time series
  exogenous_columns: # If none will use all in the table 
    # - column1
    # - column2

forecast_config:
  training_days: 30 # Optional if none use full table
  # forecast_days: 30
  table: ny_taxi_rides_h3_predict # If there is a table it will create the prediction for this data
  config_object:
    on_error: skip
    evaluate: true
    evaluation_config:
      n_splits: 2 # Default is 2
      # test_size: 30 # Defualt is null
      gap: 0
      prediction_interval: 0.95

output:
  table: taxi_forecast_results