name: Deploy Cortex Forecast SIS
on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  workflow_dispatch:

env:
  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }} # Add these secerts to github repository
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }} # Add these secerts to github repository
  SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }} # Add these secerts to github repository
  SNOWFLAKE_DATABASE: 'CORTEX' # Add these secerts to github repository
  SNOWFLAKE_SCHEMA: 'DEV' # Add these secerts to github repository
  SNOWFLAKE_WAREHOUSE: 'CORTEX_WH' # Add these secerts to github repository
  SNOWFLAKE_ROLE: 'CORTEX_USER_ROLE' # Add these secerts to github repository

jobs:
  snowflake-cli:
    name: Snowflake CLI
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Snowflake CLI
        uses: Snowflake-Labs/snowflake-cli-action@v1
        with:
          cli-version: "latest"
          default-config-file-path: "./config.toml"
        
      - name: Test Snowflake CLI
        id: TestSnowClI
        run: |
          snow --version
          snow connection set-default "default"
          snow connection test

      - name: Deploy SIS App
        id: deploy
        run: |
            snow streamlit deploy --replace


# name: "CLI Key Pair Auth testing"

# on:
#   schedule:
#     - cron: "0 0 * * *"
#   workflow_dispatch:

# jobs:
#   version:
#     name: "Check Snowflake CLI version"
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v4
#         with:
#           persist-credentials: false
#       - uses: Snowflake-Labs/snowflake-cli-action@v1
#         with:
#           cli-version: "latest"
#           default-config-file-path: "tests_integration/config/connection_configs.toml"
#       - name: Test connection
#         env:
#           TERM: unknown
#           SNOWFLAKE_CONNECTIONS_INTEGRATION_AUTHENTICATOR: SNOWFLAKE_JWT
#           SNOWFLAKE_CONNECTIONS_INTEGRATION_USER: ${{ secrets.SNOWFLAKE_USER }}
#           SNOWFLAKE_CONNECTIONS_INTEGRATION_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
#           SNOWFLAKE_CONNECTIONS_INTEGRATION_PRIVATE_KEY_RAW: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_RAW }}
#         run: snow connection test -c integration | grep Status